package semicolon.africa.waylchub.model.product;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "carts")
public class Cart {
    @Id
    private String id;

    // Sparse = true allows multiple documents to have null values for this field
    @Indexed(unique = true, sparse = true)
    private String userId;

    @Indexed(unique = true, sparse = true)
    private String sessionId; // The "Guest ID" generated by frontend

    @Builder.Default
    private List<CartItem> items = new ArrayList<>();

    private BigDecimal totalAmount;

    @Indexed(expireAfterSeconds = 2592000)
    @LastModifiedDate
    private LocalDateTime updatedAt;
}