package semicolon.africa.waylchub.model.product;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "wishlists")
public class Wishlist {
    @Id
    private String id;

    // Sparse = true allows multiple documents to have null values for this field
    @Indexed(unique = true, sparse = true)
    private String userId;

    @Indexed(unique = true, sparse = true)
    private String sessionId; // The "Guest ID" generated by frontend

    @Builder.Default
    private List<WishlistItem> items = new ArrayList<>();

    // 90 days TTL (7,776,000 seconds) - longer than cart because wishlists are long-term
    @Indexed(expireAfterSeconds = 7776000)
    @LastModifiedDate
    private LocalDateTime updatedAt;
}